version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: little-brown-book-shop-web
    volumes:
      - ./web:/web
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db/volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: LINE
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  api:
    env_file:
      - ./api/.env
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: little-brown-book-shop-api
    volumes:
      - ./api:/go/src/little-brown-book-shop
    ports:
      - "5555:5555"
    depends_on:
      - db