FROM golang:1.15-alpine
ENV GO111MODULE on
ENV GOPATH /go
ENV CGO_ENABLED 0
# live reloading
RUN go get -u github.com/cosmtrek/air
# Delve Debugger
#RUN go get github.com/go-delve/delve/cmd/dlv
WORKDIR /go/src/little-brown-book-shop
COPY . .
RUN go mod download
RUN go build -o /go/bin/lbbs ./app/main.go
ENTRYPOINT ["air","-c",".air.toml"]